### ISSUE TITLE
hi, bug

### ISSUE THREAD

**Issue by daogangtang** [richardhundt/shine#74]
mike@mike-T410s:~/GIT/shine/sample$ shine fiber.shn 
Error: [string "core"]:0: module 'async.timer' not found:
	no field package.preload['async.timer']
	no file './async/timer/init.shn'
	no file './lib/async/timer/init.shn'
	no file '/usr/local/share/shine/async/timer/init.shn'
	no file './async/timer.shn'
	no file './lib/async/timer.shn'
	no file '/usr/local/share/shine/async/timer.shn'
	no file './lib/async/timer.raw'
	no file './lib/async/timer.lua'
	no file './async/timer.lua'
	no file '/usr/local/share/tvmjit-0.1.3/async/timer.lua'
	no file '/usr/local/share/lua/5.1/async/timer.lua'
	no file '/usr/local/share/lua/5.1/async/timer/init.lua'
	no file '/usr/local/lib/shine/async/timer.so'
	no file './lib/async/timer.so'
	no file './async/timer.so'
	no file '/usr/local/lib/lua/5.1/async/timer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no module 'async.timer' in file '/usr/local/lib/shine/async.so'
stack traceback:
	[C]: in function 'require'
	[string "core"]: in function 'import'
	fiber.shn:2: in main chunk
	[string "shine"]: in main chunk
	[string "shine"]: in main chunk
	[C]: at 0x00454c60

**Comment by richardhundt** [comment]
thanks, I've removed the spurious import
