### ISSUE TITLE
hi, bug too

### ISSUE THREAD

**Issue by daogangtang** [richardhundt/shine#75]
import async from "async"

f1 = async =>
   x = 0
   for i=1, 42 do
      -- some computation
      x += 1
   end
   return x
end
print f1.join()    -- schedule until done (prints 42)

mike@mike-T410s:~/workspace/learn_shine$ shine async.shn 
Error: ./async.shn:3: attempt to call local 'async' (a table value)
stack traceback:
	./async.shn:3: in main chunk
	[C]: in function 'require'
	[string "core"]: in function 'import'
	async.shn:1: in main chunk
	[string "shine"]: in main chunk
	[string "shine"]: in main chunk
	[C]: at 0x00454c60

**Comment by richardhundt** [comment]
I can't reproduce it, this is what I see:

```
windhoek:shine richard$ cat async.shn 
import async from "async"

f1 = async =>
   x = 0
   for i=1, 42 do
      -- some computation
      x += 1
   end
   return x
end
print f1.join() -- schedule until done (prints 42)
windhoek:shine richard$ shine async.shn 
42
```

**Comment by richardhundt** [comment]
okay, I've managed to reproduce it - there's a conflict with having the file named `async` and then doing `import ... from 'async' - you end up loading the current module because files in the current directory take precedence over installed modules.

**Comment by richardhundt** [comment]
incidentally, this doesn't work with Lua either, however you'd get 

```
luajit: ./foo.lua:1: loop or previous error loading module 'foo'
```

so I guess Shine should also raise an error in this case

**Comment by daogangtang** [comment]
:D , it make sense.
