### ISSUE TITLE
Bugfix: _xstat / _xfstat / _lfstat on Linux

### ISSUE THREAD

**Issue by tarkin000** [richardhundt/shine#80]
I'm not sure how active you still are with this repo,
but in case you or anyone else hits this bug....

lib/sys/ffi/linux.shn has two bugs:
  - the *stat calls are only defined if `ffi:arch = 'arm'`
  - the _xfstat should take an `int` for a file descriptor, not `char *`

File with comments & fixes:
https://gist.github.com/tarkin000/f6af1748e7bd56d1097feb4453463730

**Comment by richardhundt** [comment]
Thanks for this, I'll take a look. I remember struggling with this part of the ABI. In future, a pull request would be nice. Just sayin'.

**Comment by richardhundt** [comment]
Seems fixed now, closing.
