### ISSUE TITLE
"tonumber" used but not defined

### ISSUE THREAD

**Issue by dvv** [richardhundt/shine#81]
I'm building shine on a mips router. The process chokes at:

```
make[1]: Entering directory '/tmp/shine/shine/lib'
../boot/bin/shinec  -n "async"          async/init.shn  /tmp/shine/shine/build/async.o
../boot/bin/shinec  -n "async.fiber"    async/fiber.shn /tmp/shine/shine/build/async_fiber.o
../boot/bin/shinec  -n "async.loop"     async/loop.shn  /tmp/shine/shine/build/async_loop.o
tvmjit: /tmp/shine/shine/boot/src/shine/lang/translator.raw:0: shine: async/loop.shn:116: "tonumber" used but not defined
```

Please, give a clue where should I _define_ `tonumber`?

**Comment by richardhundt** [comment]
I can't reproduce this. However, it looks like an issue with global symbol tracking.

You can see [here](https://github.com/richardhundt/shine/blob/master/src/lang/translator.lua#L259) these symbols are added dynamically by looping over `_G` and declaring them. You could try to add it to the `globals` table manually, but my guess is there's something else going on. Why isn't `tonumber` available in `_G`?

**Comment by dvv** [comment]
The issue might come because of luajit for mips.
I had to give up since their libc doesn't expose `dlopen` which is required to loas modules.
Sorry for buzz
